### ISSUE TITLE
test

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/SwarmCityConcept#19]

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 50.00
Contract address: [0xb50fbd81099f4ef73a658f7c4874e6029abb4c1d](https://etherscan.io/address/0xb50fbd81099f4ef73a658f7c4874e6029abb4c1d)
Network: Mainnet
Paid to: kikipluche
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
