### ISSUE TITLE
As a user, I can see all the items in a hashtag, so I know the activity of myself and other people.

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/SwarmCityConcept#8]
## Abstract:
In Swarm City, hashtags are marketplaces. A hashtag gives context to a SWT transfer.

Users (Seekers) can post new requests in a hashtag, inviting other users (Providers) to reply to their requests.

## How it could work:
A hashtag has a chronological list of hashtag items. 
It shows a user the activity in the market, including what is being requested and the offered amount. 

When a user creates or responds to an item it appears to that user above the hashtag items list. 

The list is generated by the API by listening to events on a hashtag contract. The front end creates two lists: hashtagMyItems and hashtagItems.

The API emits a update event every 5 seconds with the full dataset.

## What it looks like:

Userflow: https://invis.io/ABGM89SX3V5#/293466623_-Hashtag--contractadress_Of_The_Hashtag-

---
**route:** /hashtag/(contractadress of the hashtag)

<img src="https://i.imgur.com/lxmUj0V.png" width="450px">

In hashtag-view, we see two lists (below the hashtag + infobox), seperated by a white-space:

- **list (A) - hashtagMyItems:** A list with active items a user is involved in. If a user doesn't have active items, this list is not shown. Once a deal is being completed, the item is considered not active, so it appears as a completed deal in list 2.
- **list (B) - hashtagItems:** A list of items which a user is not involved in, and the user's completed deals.

Each hashtagItem consist of:
- description of the request
- reply-icon showing the amount of replies
- relative time
- avatar
- username and Seeker SWR*
*(visually presented simply as 'SWR' > the color of name and rep is determined by the Seeker of the item: if the current user is the Seeker, the name+rep is black. If someone else is the Seeker the name is blue)*
- In list (A): copy "No provider selected."
- copy "SWT" and the value of this item

**Scroll-behaviour list (A):**
As a user scrolls down the page /hashtag and list 1 gets out of view, a small button appears in the right top corner, showing the number of items in list 1, followed by copy "active" and a small up-icon. Tapping this button makes the page scroll up so list 1 is visible again.

<img src="https://user-images.githubusercontent.com/24499354/39828481-297eaa28-5389-11e8-9da9-592d24a94f9b.png" width="700px">

---

**Desktop view:**

<img src="https://user-images.githubusercontent.com/24499354/39735307-056458c2-5249-11e8-9b9b-01cd037a501d.png" width="700px">
<img src="https://user-images.githubusercontent.com/24499354/39735328-1ce3e526-5249-11e8-8f5a-b6b66409fcd7.png" width="700px">
---

**Invisionlinks with login (for inspect mode!):**
mobile: https://projects.invisionapp.com/d/main#/console/13838256/293466623/preview
desktop: https://projects.invisionapp.com/d/main#/console/14147648/294446454/inspect

**Comment by faffydee** [comment]
@kikipluche @kingflurkel In the comment above an error occured:

In section: **What it looks like**, it now says:
username and Seeker SWR* (black in list 1 (hashtagMyItems), blue in list 2 (hashtagItems)
*(visually presented simply as 'SWR')

This is wrong. The color of the username and Seeker SWR is not dependant, it depends on who is the Seeker of the item: if I, the current user, is the Seeker, my name is black. If someone else is the Seeker the name is blue.

As a matter of fact, it is always this way throug out the app: when my (= the current users) name and rep is shown, it is black. When someone else's username and rep is shown, it is blue, always, in any case.

**Comment by kikipluche** [comment]
@faffydee @kingflurkel I adapted the epic with all changes that are approved and faffy's remark.

**Comment by xardass** [comment]
> The list is generated by listening to events on a hashtag contract.

I suppose this is done on the node, and front-end has a channel to subscribe to?

**Comment by kikipluche** [comment]
- [x] faffy puts the filter button back on the view where list A is scrolled up.

**Comment by kikipluche** [comment]
how it works:
frontend goes on hashtag and starts a subscription on that hashtag.
frontend gets back from API: datasets of all items on that hashtag and all replies connected to those items
frontend will filter this list to list A or B 
the API will emit an event every 5 seconds with the latest full dataset.

**Comment by faffydee** [comment]
@kikipluche Done!
