### ISSUE TITLE
As a user, I see the detail-view of a request/deal so I can verify all the details of this request/deal.

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/SwarmCityConcept#9]
## Abstract:
In Swarm City, hashtags are marketplaces. A hashtag gives context to a SWT token transfer.

Users (Seekers) can post new requests in a hashtag, inviting other users (Providers) to reply to their requests.

## How it could work:
A hashtag has a chronological list of hashtag items.
When the user taps the item, a detailed view is displayed.

The client gets real-time updates on the detail state. The client subscribes to the item. 

There are 2 types of detail views:
- **Item**: the user is not engaged in this item
- **My Item**: the user is engaged in this item

### Shareable link
In both views a user sees a shareable link to the detail view of the item.

This link can be shared on social platforms to advertise it.

The detail view contains the appropriate meta tags to render a preview on most social media and content platforms.

It could look like this:
`https://swarm.city/hashtag/[contractaddress]/[dealhash]`

-------

## What it looks like:

Userflow: https://invis.io/ABGM89SX3V5#/293478690_-Hashtag--contractadress---dealhash-_MYITEM
*( > in Invision, hold shift to see clickable areas)*

---

**route:** /hashtag/[hashtagadress]/[itemhash]

The item's appearance changes depending on the user's role:

<img src="https://i.imgur.com/yyuyGhe.png" width="700px">

**Detail view - myItem (A):**
When the user is the Seeker, the item consists of:
- hastag + infobox
- x-mark (detail close-button)
- description
- dateTime
- avatar
- name and "•" and SeekerRep* (black)
*(visually presented just as 'SWR')*
- copy "SWT" and the value of this item
- shareable link
- dotted divider line
- replies (when no replies: copy "No replies yet.")
- cancel-button (copy:"cancel this request")

**Detail view - Item (B):**
When the user is not the Seeker:
* The item consists of:
* hashtag + infobox
* x-mark (detail close-button)
* description
* dateTime
* avatar
* name and "•" and SeekerRep* (blue)
*(visually presented just as 'SWR')*
- copy "SWT" and the value of this item
- shareable link
- dotted divider line
- replies (when no replies: copy "No replies yet.")
- big white button with blue reply-icon

When the user taps the detail close-button (x-mark), the view changes to the page /hashtag/[contractaddress].

---

**Desktop view:**
<img src="https://i.imgur.com/Dglfiav.png" width="700px">
<img src="https://i.imgur.com/xHSFtTE.png" width="700px">

---

**Invisionlinks with login (for inspect mode!):**
mobile: https://projects.invisionapp.com/d/main#/console/13838256/293478690/inspect
desktop: https://projects.invisionapp.com/d/main#/console/14147648/294446445/inspect
## Documentation / references
Detail-view meta for shareable link:

```htmlmixed=
<!-- For Google -->
<meta name="description" content="" />
<meta name="keywords" content="" />

<meta name="author" content="" />
<meta name="copyright" content="" />
<meta name="application-name" content="" />

<!-- For Facebook -->
<meta property="og:title" content="" />
<meta property="og:type" content="article" />
<meta property="og:image" content="" />
<meta property="og:url" content="" />
<meta property="og:description" content="" />

<!-- For Twitter -->
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="" />
<meta name="twitter:description" content="" />
<meta name="twitter:image" content="" />
```
♡

**Comment by kingflurkel** [comment]
Matt and I edited this epic: 

# As a user, I see the detail-view of a request/deal so I can verify its information

## Abstract:
In Swarm City, hashtags are marketplaces. A hashtag gives context to a SWT token transfer.

Users (seekers) can post new requests in a hashtag, inviting other users (providers) to reply to their requests.

## How it could work:
A hashtag has a chronological list of hashtag items.
When the user taps the item, a detailed view is displayed.

The client gets real-time updates on the detail state.

There are 2 types of detail views: 
- **Item:** the user is not engaged in this item
- **My Item:** the user is engaged in this item

### Shareable link ###
In both views a user sees a shareable link to the detail view of the item.

This link can be shared on social platforms to advertise it.

The detail view contains the appropriate meta tags to render a preview on most social media and content platforms.

It could look like this:
```https://swarm.city/hashtag/[contractaddress]/[dealhash]```

### Data model ###
This is the proposed datamodel for an item:
```json=
{
 "dealHash": "123abc", // generated using sha3(dealId),
 "name": "Tester X",    //username of sender
 "avatar" : <IPFSHASH>,    // the IPFS hash of the users' avatar
 "address" : "0x123...abc" // the ETH address of the user
 "balance": "25000000000000000000",    //balance in SWT of the user at the time of creation
 "repBalance": "25000000000000000000", //the balance of the seekerRep at the time of creation
 "description": "Translate my 1 page manifesto from English to Dutch",    // description of the deal
 "dateTime": "1519846041301",    // timestamp when this deal was created on the client
 "value": "15000000000000000000",    // value of this deal
 "hashtag": "0xfa12..."            // the contract address of the hashtag where this is posted.
 "hashtagFee": "123992"    // the hashtag fee applied to this deal
}
```
-------

## What it could look like:

**route:** /hashtag/[contractadress]/[dealhash]

The item's appearance changes depending on the user's role:

**Detail view - Item:**
When the user is not the Seeker:

![Detail view - not my item](https://i.imgur.com/ZFBy4un.png)

The item consists of:
- hashtag + infobox
- x-mark (detail close-button)
- description
- dateTime
- avatar
- name and "•" and SeekerRep* (blue)
*(visually presented just as 'SWR')
- copy "SWT" and the value of this item
- shareable link
- dotted divider line
- replies (when no replies: copy "No replies yet")
- big white button with blue reply-icon

**Detail view - myItem:**
When the user is the Seeker:

![Detail view - my item](https://i.imgur.com/5C7jCYf.png)

The item consists of:
- hastag + infobox
- x-mark (detail close-button)
- description
- dateTime
- avatar
- name and "•" and SeekerRep* (black)
*(visually presented just as 'SWR')
- copy "SWT" and the value of this item
- shareable link
- dotted divider line
- replies (when no replies: copy "No replies yet")
- cancel-button (copy:"cancel this request")

When the user taps the detail close-button (x-mark), the view changes to the page /hashtag/[contractaddress].

## Documentation / references
Detail-view meta for shareable link:

```htmlmixed=
<!-- For Google -->
<meta name="description" content="" />
<meta name="keywords" content="" />

<meta name="author" content="" />
<meta name="copyright" content="" />
<meta name="application-name" content="" />

<!-- For Facebook -->
<meta property="og:title" content="" />
<meta property="og:type" content="article" />
<meta property="og:image" content="" />
<meta property="og:url" content="" />
<meta property="og:description" content="" />

<!-- For Twitter -->
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="" />
<meta name="twitter:description" content="" />
<meta name="twitter:image" content="" />
```
♡

**Comment by kikipluche** [comment]
I replaced the epic with the edited version

**Comment by xardass** [comment]
item needs a state property (open, accepted, conflict...)

**Comment by kikipluche** [comment]
in the API will have a subscription on 1 item and it will emit updates

**Comment by xardass** [comment]
When landing on an item detail page, the client will start a new subscription to the API with real-time updates on this item. 

When closing the detail view, route to the corresponding hashtag page (which can be found within the item detail direct URL)
